#!/bin/sh
set -e
# Update desktop database and icons
if [ -x /usr/bin/update-desktop-database ]; then
    /usr/bin/update-desktop-database
fi
if [ -x /usr/bin/xdg-icon-resource ]; then
    /usr/bin/xdg-icon-resource install --size 64 /usr/share/icons/hicolor/64x64/apps/gitflow-studio.png gitflow-studio
fi
# Onboarding or migration steps can be added here
exit 0 